### ISSUE TITLE
Module Fails with Self-Signed Vault Certificate 

### ISSUE THREAD

**Issue by fia5000** [TerryHowe/ansible-modules-hashivault#10]
So it appears that this module fails when you have a Vault deployment that is using a self-signed certificate/TLS
`TASK [Read values] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)", "rc": 1}`

Is there a workaround possible or perhaps the ability to `validate_certs: false` like other ansible modules?

It seems the only way around this is by setting VAULT_SKIP_VERIFY; it would be nice to be able to set this in the playbook itself.

**Comment by TerryHowe** [comment]
I thought there was a way to do this, but I'll have to investigate.

**Comment by TerryHowe** [comment]
This should do it https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_read.py#L14

**Comment by rattermeyer** [comment]
The verify = False removes the error, but does not resolve the problem.
Especially as this is a security related module, I would like not to turn off verification, but enable to specify / whitelist the CA cert. This could be done using VAULT_CACERT or _CAPATH (see https://www.vaultproject.io/docs/commands/environment.html).
Haven't tested the lookup module, but it seems you are using there the VAULT_CAPATH already.

**Comment by TerryHowe** [comment]
Okay, maybe it isn't documented clearly enough, but this module uses hvac to access vaulty and hvac uses requests.  Requests takes verify as a boolean or a string to the capath.  I haven't tested it, but it *should* work:

http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification

**Comment by TerryHowe** [comment]
The lookup plugin is a little nicer about defaulting verify: https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/plugins/lookup/hashivault.py#L37

**Comment by rattermeyer** [comment]
Hi, 
that's what I understood as well, so I tried:

    hashivault_status:
      verify: /etc/ssl/certs/cluster-ca.pem

But this results in /etc/ssl/certs/cluster-ca.pem is not a valid boolean. Valid booleans include: y,yes,on,1,true,1,True,n,no,off,0,false,0,False"

which might come from hashivault_argspec / _init:
verify = dict(required=False, default=(not os.environ.get('VAULT_SKIP_VERIFY', '')), type='bool'),

or maybe I am missing something.

**Comment by TerryHowe** [comment]
Could you do my a favor and remove the type specified in that line from within you venv and let me know if it works.  If that doesn't work, tryp type='str'.  I don't have anything to test that right now and setting up a system to test that would be time consuming.

**Comment by rattermeyer** [comment]
Hi,
will give it a try. Need to understand how to "develop" ansible module. Might take some days until I find time...

**Comment by TerryHowe** [comment]
No need to do real development, just edit the file in your venv directly most likely something like editing the file $VIRTUAL_ENV/lib/python2.7/site-packages/ansible/module_utils/hashivault.py and edited line 12 I think:
`verify = dict(required=False, default=(not os.environ.get('VAULT_SKIP_VERIFY', '')), type='str'),`

**Comment by dizzler** [comment]
Improved support for TLS via hvac is in PR #32  [https://github.com/TerryHowe/ansible-modules-hashivault/pull/32](url)

**Comment by TerryHowe** [comment]
https://pypi.python.org/pypi/ansible-modules-hashivault it is live
