### ISSUE TITLE
encrypted pem file support

### ISSUE THREAD

**Issue by MrAmbiG** [TerryHowe/ansible-modules-hashivault#102]
ex:- VAULT_CLIENT_CERT="/opt/vault/cert.pem:pem_passphrase"
If the variable is set like the above then the one after the : should be taken as the passphrase, since currently some applications do accept pem files in this format.

**Comment by TerryHowe** [comment]
Related https://github.com/psf/requests/issues/1573

**Comment by TerryHowe** [comment]
It looks like an X509 adapter would have to be constructed, a requests session constructed, and that session would have to be passed to hvac.Client(session=mysession) right around here https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/module_utils/hashivault.py#L86

I'm not terribly thrilled with this idea as I don't think we should be messing with what layer, hvac should deal with it.

**Comment by TerryHowe** [comment]
Closing this as an hvac issue
