### ISSUE TITLE
Check if key is already set

### ISSUE THREAD

**Issue by ushacow** [TerryHowe/ansible-modules-hashivault#104]
Hi! 

Are there any check if key is already exist in vault when I'm using hashivault_write?

**Comment by TerryHowe** [comment]
There is an update option to hashivault_write that will read first and only set changed if it actually changes something.

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_write.py#L56

If that isn't what you are looking for, if you want to see if it is set to *any* value then, you'll have to read it yourself first.
