### ISSUE TITLE
Use Variables in Key when Writing Secrets

### ISSUE THREAD

**Issue by fia5000** [TerryHowe/ansible-modules-hashivault#11]
**What:**
It appears that when writing a secret, the key you are writing cannot be or contain an ansible variable. 

**Example:**
- name: Store some password in HVAULT
  hashivault_write:
    url: "{{HVAULT_URL}}"
    verify: false
    authtype: userpass
    username: ansible
    password: "{{HVAULT_PASS}}"
    secret: '{{Group|upper}}/{{Env_Tier|upper}}'
    data:
      **"someuser{{ User_Suffix }}"**: "{{ someuser_Password }}"
  delegate_to: localhost

**Expected Results:**

under- 
data:
**"someuser{{ User_Suffix }}"**: "{{ someuser_Password }}"

The module should be able to append whatever the value of {{User_Suffix}} is to the key it writes in Hashicorp Vault.  So if the value of {{User_Suffix}} is `P` the module should write the secret in Vault as `someuserP`.

**Actual Results**
In testing, the module is writing the literal string `someuser{{ User_Suffix }}` as the KEY in Vault, even though the value is correctly written in Vault as the variable value for `{{ someuser_Password }}`

**Comment by TerryHowe** [comment]
This issue keeps coming up and it is an ansible issue.  Here is a former issue with some discussion on workarounds: https://github.com/TerryHowe/ansible-modules-hashivault/issues/9
