### ISSUE TITLE
3.12.1 doesnt include the PR changes for version param

### ISSUE THREAD

**Issue by drewmullen** [TerryHowe/ansible-modules-hashivault#113]
take a look at the tag 3.12.1 files and look at the `hashivault_write.py`. that file doesn't include the new `version` parameter. seems like something went bad during packaging

**Comment by drewmullen** [comment]
https://github.com/TerryHowe/ansible-modules-hashivault/pull/111

**Comment by TerryHowe** [comment]
I just haven't released it yet.

**Comment by drewmullen** [comment]
oh, sorry - im curious how that works. i see the tag in the repo and also was able to download 3.12.1 through pypi. assumed that meant it was released but ive never released anything to pypi b4. got any recommendations on reading?

**Comment by TerryHowe** [comment]
3.12.1 was released, kv2 support isn't in it.

If you go to the tag and brown the files by the commit https://github.com/TerryHowe/ansible-modules-hashivault/blob/8dddbfd514f76a1735a87dec5f7203de6fcb3a5f/ansible/modules/hashivault/hashivault_read.py

You'll see that guy doesn't have kv2 support.

I was messing with `client.secrets.kv.v2.read_secret_version(secret, mount_point=mount_point)` this morning.  Good progress on the read and lookup plugin.  I still need to get around to the write and delete way of doing that.

**Comment by TerryHowe** [comment]
At your suggestion, I did this https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_read.py

I added a mount_point parameter and default to /secret like it was previously.  I thought it came out pretty nice.

**Comment by drewmullen** [comment]
AH, i see what i did. next to the release link it says "37 commits to master since". reading too quickly, i thought that was a link to INCLUDED commits of the release. my bad!
![image](https://user-images.githubusercontent.com/3812162/52055145-6c1da800-2513-11e9-8bcb-1fc47050f83a.png)

good call, IMO. no need to force ppl to use `secret`

looking forward to your changes with the newer hvac v2 endpoints. although i dont like you stealing my fake internet points, rewriting my code (*GLARE*) (kidding) :)
