### ISSUE TITLE
hashivault_init should accept recovery_shares and recovery_threshold as arguments

### ISSUE THREAD

**Issue by kdask** [TerryHowe/ansible-modules-hashivault#116]
Currently it's not possible to initialize vault with configured autounseal using `hashivault_init`. 

I've tested it with [awskms seal](https://learn.hashicorp.com/vault/operations/ops-autounseal-aws-kms) :

**_vault.hcl_**
```
backend "consul" {
  address = "127.0.0.1:8500"
  advertise_addr = "http://1.2.3.4:8200"
  path = "vault"
  scheme = "http"
}

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = 1
}

seal "awskms" {
  kms_key_id = "alias/vault"
  region     = "us-west-2"
}

disable_mlock = 1
```

**_Ansible task:_**
```
- name: Initialize
  hashivault_init:
    url: "http://1.2.3.4:8200"
```

When running it, I'm getting the following error:
```    
    TASK [vault : Initialize] ******************************************************
    fatal: [vault-1]: FAILED! => changed=false 
      msg: 'Exception: recovery configuration must specify a positive number of shares'
      rc: 1
```

But `hashivault_init` doesn't accept [recovery_shares](https://www.vaultproject.io/api/system/init.html#recovery_shares) and [recovery_threshold](https://www.vaultproject.io/api/system/init.html#recovery_threshold) as parameters.

**_CLI works as expected:_**
```
$ vault operator init
Recovery Key 1: tRwgdu0eM6x4JSJr3f4uhQjsOdHDUCXc2jkb9QEF15Px
<...>
Recovery Key 5: qpcm5081oVKNtFuClT9Gxvw8Vht34n/h4Gw9UnZLEqSV

Initial Root Token: <...>

Success! Vault is initialized

Recovery key initialized with 5 key shares and a key threshold of 3. Please
securely distribute the key shares printed above.
```

**Note:** currently there is another opened issue in **hvac** which makes it impossible to pass `recovery_shares` and `recovery_threshold` to Vault API: https://github.com/hvac/hvac/issues/394

**Comment by TerryHowe** [comment]
Those parameters should be added to the module.  The feature just is not available right now.

**Comment by TerryHowe** [comment]
I added these arguments to 3.16.2 released just now, but I have no way of testing, so let me know if you have any issues.

**Comment by DaazKu** [comment]
@TerryHowe 

> parameters secret_shares,secret_threshold not applicable to seal type awskms

```
  hashivault_init:
    recovery_shares: 5
    recovery_threshold: 3
 ```

Doesn't seem to be working.

Also, because of the type requirement,
```
  hashivault_init:
    recovery_shares: 5
    recovery_threshold: 3
    secret_shares: None
    secret_threshold: None
```
```
  hashivault_init:
    recovery_shares: 5
    recovery_threshold: 3
    secret_shares: ""
    secret_threshold: ""
```
do not work.

I had to modify the following:
https://github.com/TerryHowe/ansible-modules-hashivault/blob/449fdfef6e59cbd2a6d88ccf20435037528153bc/ansible/modules/hashivault/hashivault_init.py#L66-L67
to
```
    argspec['secret_shares'] = dict(required=False, type='int', default=None)
    argspec['secret_threshold'] = dict(required=False, type='int', default=None)
```

You probably want to maintain the default. Any chance you can fix it?
