### ISSUE TITLE
Lease information to hashivault_read result

### ISSUE THREAD

**Issue by eeroniemi** [TerryHowe/ansible-modules-hashivault#122]
I'm using Vault to to generate GCP service accounts (https://www.vaultproject.io/docs/secrets/gcp/index.html), and my plan was to use this module to create and manage these created keys. It looks like hashivault_read module's response is missing critical lease information (lease_id) so that I could accomplish my goal (renewing the tokens in crontab).

For example, if I create new service account using Vault CLI I get the lease_id:

```
vault read gcp/key/testkey
Key                 Value
---                 -----
lease_id            gcp/key/testkey/rLArJn3j1dLpEgRuYAhz1dbw
lease_duration      10m
lease_renewable     true
key_algorithm       KEY_ALG_RSA_2048
key_type            TYPE_GOOGLE_CREDENTIALS_FILE
private_key_data    ewogICJ0eXBlIjogInNlcnZp...
```

But when I do the same with hashivault_read Ansible module:

```
- name: Create service account key
  hashivault_read:
    secret: "key/testkey"
    mount_point: "gcp"
```

The result is missing lease_id:

```
TASK [vault-credential-key : debug service account key] ************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1] => {
    "msg": {
        "changed": false, 
        "failed": false, 
        "rc": 0, 
        "value": {
            "key_algorithm": "KEY_ALG_RSA_2048", 
            "key_type": "TYPE_GOOGLE_CREDENTIALS_FILE", 
            "private_key_data": "ewogICJ0eXBlIjogInNlcnZp..."
        }
    }
}
```

It looks like the Python HVAC library provides this information, with this kind of Python test script:

```
vault_client = hvac.Client(url=vault_url, token=vault_token, timeout=3, verify=vault_verify, cert=vault_cert)
key_path = 'gcp/key/testkey'
data = vault_client.read(key_path)
print(data)
```

Data has lease_id:

```
{u'lease_id': u'gcp/key/testkey/LDBb2ziaPZmRN22TaTVD3Lji', u'warnings': None, u'wrap_info': None, u'auth': None, u'lease_duration': 600, u'request_id': u'9c72cc7c-9139-9c1e-347a-6ac134abc426', u'data': {u'key_type': u'TYPE_GOOGLE_CREDENTIALS_FILE', u'key_algorithm': u'KEY_ALG_RSA_2048', u'private_key_data': u'ewogICJ0eXBlIjogInNlcnZp...'}, u'renewable': True}
```

It would be nice to get this lease_id (and maybe other metadata also, lease duration etc?) into hashivault_read result.

This looks like quite simple code change in ansible.module_utils.hashivault.hashivault_read function ([here](https://github.com/TerryHowe/ansible-modules-hashivault/blob/3a8b735a7cfe97e71dd1aaa5951cf1078ce7e1b3/ansible/module_utils/hashivault.py#L126-L188)) and I could probably help by providing PR, but I'm not totally sure what would be correct place for this information, inside "value" dict or somewhere else?

**Comment by TerryHowe** [comment]
Either in value or just lease_id and lease_duration should just be added to the response similar to the way data is added after https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/module_utils/hashivault.py#L169 . I don't have a strong argument one way or the other.

**Comment by TerryHowe** [comment]
https://github.com/TerryHowe/ansible-modules-hashivault/commit/5c408d3017a524063baf4da44090eb182dc83fbf

```
TASK [Read the kv2 value] *****************************************************************************************************************************************************
ok: [localhost] => {"changed": false, "lease_duration": 604800, "lease_id": "", "rc": 0, "renewable": false, "value": "kv2_stuff"}
```

**Comment by TerryHowe** [comment]
Okay, I managed to make a similar change to support that for v1 https://github.com/TerryHowe/ansible-modules-hashivault/commit/ae5afa01ac77d2de1606454ce36e047c10c01314 

Closing this out

**Comment by TerryHowe** [comment]
Release 3.17.1 by the way.
