### ISSUE TITLE
azure and database modules

### ISSUE THREAD

**Issue by drewmullen** [TerryHowe/ansible-modules-hashivault#129]
hey terry,

I'm working on some azure and database modules:
- ~azure secrets engine config - `hashivault_azure_secret_engine_config`~ https://github.com/TerryHowe/ansible-modules-hashivault/pull/130
- ~azure secrets engine role write - `hashivault_azure_secret_engine_role`~ https://github.com/TerryHowe/ansible-modules-hashivault/pull/130
- ~azure auth config - `hashivault_azure_auth_config`~ https://github.com/TerryHowe/ansible-modules-hashivault/pull/132
- ~azure auth role write - `hashivault_azure_auth_role`~ https://github.com/TerryHowe/ansible-modules-hashivault/pull/132
- ~database config - `hashivault_database_config`~ https://github.com/TerryHowe/ansible-modules-hashivault/pull/133
- ~database role- `hashivault_database_role`~ https://github.com/TerryHowe/ansible-modules-hashivault/pull/133

I wanted to ask for consensus in naming (above) and also spread awareness that im working on these. 

all will take either parameters or a json file containing the required params

finally, im not sure how we'll fully test the database config since it would actually require a database to exist in test env but ill try to get as much testing as possible

**Comment by TerryHowe** [comment]
Looks good, thanks.  I don't think testing anything on Azure at least is going to be practical.

**Comment by drewmullen** [comment]
yeah thats a good point. likely cant test on either. ill run it through my own tests and provide guidance on future testing

**Comment by drewmullen** [comment]
close by prs mentioned in overview
