### ISSUE TITLE
hashivault_auth_disable doesnt exist

### ISSUE THREAD

**Issue by drewmullen** [TerryHowe/ansible-modules-hashivault#131]
we need an auth disable module, at the very least for testing

personally, i recommend just adding `hashivault_auth_backend` and include a `{'state': 'enabled' or 'disabled'}`

i can add this to my todo list if you're okay with that design implementation

**Comment by TerryHowe** [comment]
Sounds good

**Comment by TerryHowe** [comment]
Thanks released 👍
