### ISSUE TITLE
use no_log=True for sensitive module parameters

### ISSUE THREAD

**Issue by Andrean** [TerryHowe/ansible-modules-hashivault#135]
Hi!

If I run playbook in verbose mode or if playbook failed on tasks hashivault_write something, ansible shows all sensitive information in log, including contents if 'data', 'password', 'token'

    "changed": false,
    "invocation": {
        "module_args": {
            "authtype": "userpass",
            "ca_cert": "",
            "ca_path": "",
            "client_cert": "",
            "client_key": "",
            "data": {
                "key1": "SENSITIVE_INFORMATION",
                "key2": "SENSITIVE_INFORMATION",
                "key3": "SENSITIVE_INFORMATION"
            },
            "mount_point": "secret",
            "namespace": null,
            "password": "SENSITIVE_INFORMATION",
            "role_id": "",
            "secret": "my/path/to/secret",
            "secret_id": "",
            "token": "SENSITIVE_INFORMATION",
            "update": true,
            "url": "http://vault.localhost",
            "username": "user",
            "verify": true,
            "version": 2
     }

**Comment by drewmullen** [comment]
this is a really good recommendation. i forgot ansible has that feature

example of how to implement:
```
def main():
    module = AnsibleModule(
        argument_spec=dict(
            password=dict(type='str', no_log='true')
        )
    ...
```

**Comment by drewmullen** [comment]
so it looks like ive implemented both ways (`True` and `'true'`) so ansible must handle for the type... not sure why its still showing the token in verbose output

will continue to investigate as i can

**Comment by TerryHowe** [comment]
I feel like I'ver seen this before, but related I think https://github.com/ansible/ansible/issues/11253

**Comment by TerryHowe** [comment]
I enabled no_log for the data in the write, but from what I read we can't prevent some of that data from logging for debugging, so no_log is limited.  The changes will be release on 3.18.1
