### ISSUE TITLE
hashivault_approle_role_create does not support path option version=< 3.17.7

### ISSUE THREAD

**Issue by codeselim** [TerryHowe/ansible-modules-hashivault#139]
The hashivault_approle_role_create does not allow a user to specify an auth path different than the default one. The path that is used is the default one "approle"
Using version: 3.17.7

**Comment by TerryHowe** [comment]
https://github.com/TerryHowe/ansible-modules-hashivault/commit/d8db3d47bb20cf7afc4a94287edddbcb86067a58

Released soon probably on a 4.0.0 release

**Comment by TerryHowe** [comment]
https://github.com/TerryHowe/ansible-modules-hashivault/pull/148

**Comment by TerryHowe** [comment]
Released 4.0.0
