### ISSUE TITLE
Using hashivault_write to configure certs

### ISSUE THREAD

**Issue by bchannak** [TerryHowe/ansible-modules-hashivault#14]
Hi,
I am trying to add a cert policy like below:

    - name: Configure cert backend with cert & policy
      hashivault_write:
        url: "{{ vault_addr }}"
        verify: no
        token: "{{ vault_token }}"
        secret: "/auth/cert/certs/intermediate_ca"
        data:
          display_name: intermediate_ca 
          policies: test
          certificate: \@/vault/etc/vault-intermediate-ca.cert.pem

The error I am running into is "fatal: [10.0.38.225]: FAILED! => {"changed": false, "failed": true, "msg": "Exception: failed to parse certificate", "rc": 1}". Am I missing something?

There are several other configs using hashivault module that is going fine.

If I execute the following directly, it looks like working. So I am pretty sure that the cert itself is proper and the permission, etc are valid.

vault write auth/cert/certs/intermediate_ca \
    display_name=intermediate_ca \
    policies=test\
    certificate=@/vault/etc/vault-intermediate-ca.cert.pem

I am using ansible-playbook v2.2.1.0

Additional info (with -vvv):

fatal: [<IP Address removed>]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "authtype": "token", 
            "data": {
                "certificate": "\\@/vault/etc/vault-intermediate-ca.cert.pem", 
                "display_name": "intermediate_ca", 
                "policies": "test"
            }, 
            "password": null, 
            "secret": "/auth/cert/certs/intermediate_ca", 
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "update": false, 
            "url": "https://vault.andromeda.cisco.local:8200", 
            "username": null, 
            "verify": false
        }, 
        "module_name": "hashivault_write"
    }, 
    "msg": "Exception: failed to parse certificate", 
    "rc": 1
}

**Comment by TerryHowe** [comment]
Where did that  \@/vault/etc/vault-intermediate-ca.cert.pem syntax come from?  Is that some ansible shorthand I'm not familiar with?  I would expected the file lookup:

    certificate: "{{ lookup('file', '/vault/etc/vault-intermediate-ca.cert.pem') }}"

**Comment by bchannak** [comment]
Hi Terry,
Thanks for your response. This is coming from vault docs (i guess specific to vault). Here are some of the pointers:
https://www.vaultproject.io/docs/auth/cert.html
https://www.vaultproject.io/docs/commands/read-write.html

I will try your suggestion and let you know.

**Comment by bchannak** [comment]
Hi Terry,
Your suggestion certainly works, good for now. Appreciate your quick response!

**Comment by TerryHowe** [comment]
Yeh, that is a cli thing.  I think most people would expect to use the file lookup if they are coming from the ansible world.
