### ISSUE TITLE
idempotence checks may be affected by 1.4 update

### ISSUE THREAD

**Issue by drewmullen** [TerryHowe/ansible-modules-hashivault#144]
vault 1.4 is likely to introduce many breaking changes: https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#120-july-30th-2019

Token store roles use new, common token fields for the values that overlap with other auth backends. period, explicit_max_ttl, and bound_cidrs will continue to work, with priority being given to the token_ prefixed versions of those parameters. They will also be returned when doing a read on the role if they were used to provide values initially; however, in Vault 1.4 if period or explicit_max_ttl is zero they will no longer be returned. (explicit_max_ttl was already not returned if empty.)

**Comment by TerryHowe** [comment]
It'd be nice if they used normal semantic versioning so this would be more obvious to look for.  Thanks for the heads up.

**Comment by drewmullen** [comment]
i noticed that `hashivault_secret_engine` is no longer idempotent, i believe this is the cause. need to investigate

**Comment by TerryHowe** [comment]
I've worked through a couple of these and I think we ought to handle them as they are identified. Some don't support update at the moment anyway.
