### ISSUE TITLE
Allow setting header for AWS auth method

### ISSUE THREAD

**Issue by tomi-roam** [TerryHowe/ansible-modules-hashivault#153]
I couldn't find a way to specify the header value for `X-Vault-AWS-IAM-Server-ID` that can be configured to be required on Vault login to prevent replay attacks (https://www.vaultproject.io/docs/auth/aws.html).

Looks like `hvac` has this supported when creating the client (https://hvac.readthedocs.io/en/stable/usage/auth_methods/aws.html) by passing in the value with the `header_value` argument.

Any chance to get this added?

**Comment by drewmullen** [comment]
looks like we're not even using the direct aws methods: https://github.com/TerryHowe/ansible-modules-hashivault/blob/bda1f55e1fbb56e53ebd4a3eb1deef5da341eaa8/ansible/modules/hashivault/hashivault_aws_ec2_role_create.py#L193

aws methods from hvac: https://github.com/hvac/hvac/blob/develop/hvac/api/auth_methods/aws.py

so this change might take a rewrite. im not super familiar with aws auth

**Comment by drewmullen** [comment]
Fyi I'm working on a rewrite of aws auth module this week

**Comment by TerryHowe** [comment]
While there is a lot of work to do provisioning aws auth as @drewmullen mentioned, the PR should cover the original ask I think
