### ISSUE TITLE
VAULT_PASSWORD field value is visible when playbook is executed with verbose flag.

### ISSUE THREAD

**Issue by dmilind** [TerryHowe/ansible-modules-hashivault#156]

**Comment by TerryHowe** [comment]
Related https://github.com/TerryHowe/ansible-modules-hashivault/issues/135

As near as I know we've disabled logging for everything we can disable logging.

- There are some things (like environment variables) ansible logs no matter what in verbose mode and you just shouldn't do that. My general recommendation is don't debug log playbooks that use hashivault.
- Specify `no_log: True` for hashivault tasks.
- Don't use user pass, use something else with an ephemeral authentication.

If you have some other particular case in mind I'm unaware of, please reopen.
