### ISSUE TITLE
hashivault_write: returned data contains ********

### ISSUE THREAD

**Issue by kongslund** [TerryHowe/ansible-modules-hashivault#162]
When requesting a certificate by writing a secret to Vault's PKI secrets engine, a result is returned containing the requested certificate, private key etc. If the result returned has a substring matching whatever was provided in `hashivault_write`'s `data` option then that substring is replaced by [`********`](https://docs.ansible.com/ansible/latest/network/user_guide/faq.html#why-is-my-output-sometimes-replaced-with) and the output is no longer usable.

As an example, if `data` contains the string `1h` for 1 hour:

```
        data:
          common_name: "test.example.com"
          ttl: "1h"
```

and the result (certificate/private key/issuing certificate/...) contains the substring `1h`

```
-----BEGIN CERTIFICATE-----
...
A4IBAQAIQFdBHN8hKaWLsST1h6M4YN2yl2tFkP3zy+ie23f5VZTB0XpFknJCaJQN
...
-----END CERTIFICATE-----
```

then the output becomes

```
-----BEGIN CERTIFICATE-----
...
A4IBAQAIQFdBHN8hKaWLsST********6M4YN2yl2tFkP3zy+ie23f5VZTB0XpFknJCaJQN
...
-----END CERTIFICATE-----
```

I believe this is caused by the change in #135.

Does this qualify as a bug or feature? 🤔 I am guessing it is not the intention to treat a string such as `1h` as a password. It could cause problems later on in a play - not just when attempting to use the returned data. Perhaps a separate pki module is needed for this kind of use case?

**Comment by drewmullen** [comment]
interesting - Looks like `data` is marked as secretive. 

https://github.com/TerryHowe/ansible-modules-hashivault/blob/7152df771ccea48c3f98e7d3997b60d8487680af/ansible/modules/hashivault/hashivault_write.py#L99

This module is VERY generic. if there are specific actions you want to complete you should either use a more specific module or iif it doesn't exist open an issue and describe the feature you want (or open a PR :)

Generally speaking, I never use this module but it does have a place for workarounds only while actually modules are being created

**Comment by drewmullen** [comment]
if theres nothing else, can we close this issue, @kongslund ?

**Comment by kongslund** [comment]
Yes, no need to keep it around. Thanks.
