### ISSUE TITLE
some configs fail when namespace doesnt exist yet

### ISSUE THREAD

**Issue by drewmullen** [TerryHowe/ansible-modules-hashivault#167]
`hashivault_azure_auth_config` fails if the namespace has not been built yet. that means `-C` does not work. i believe this can be fixed by wrapping the following code in a `try` block (or including in the try below it:

https://github.com/TerryHowe/ansible-modules-hashivault/blob/52dd34093b80026ff07eecaaa822e175867ee3af/ansible/modules/hashivault/hashivault_azure_auth_config.py#L152

I'm guessing there are many other configs that fall into this bucket as well

list of modules affected:

- [x] hashivault_azure_auth_config
- [x] hashivault_auth_method
- [x] hashivault_azure_auth_role
- [x] hashivault_database_secret_engine_config
- [x] hashivault_database_secret_engine_config
- [x] hashivault_azure_secret_engine_config
- [x] hashivault_azure_secret_engine_role
- [x] hashivault_policy_set_from_file
- [x] hashivault_approle_role
- [x] hashivault_policy_set

**Comment by drewmullen** [comment]
this occured when there were multiple calls to validate a resource  1. does the resource exists? 2. what is the existing resource current state (to compare to desired)? in most cases, one of these calls was not conditioned to except the error that occurs when no namespace exists: "404 path does not exist"

wrapping the request in a try and checking for check_mode when an error occurs is an OK fix
```
    # check if mount exists
    # if errors but check mode is enabled then pass as "changed"
    # while this is technically incorrect, its more likely helpful than hurtful
    try:
        enabled_methods = client.sys.list_auth_methods()['data'].keys()
        if (mount_point + "/") not in enabled_methods:
            return {'failed': True, 'msg': 'auth mount is not enabled', 'rc': 1}
    except:
        if module.check_mode:
            changed = True
```

there is technically 1 issue with this solution. if a namespace doesnt exist and a user uses `-C`, _technically_ ansible is telling them a state would "change" when it in fact would fail. however, the gains from having a _functioning check mode_ far outweigh the small use cases of check mode showing a false positive IMO

**Comment by TerryHowe** [comment]
https://github.com/TerryHowe/ansible-modules-hashivault/pull/226

Discovered that the update_role method had been deleted, but it inadvertently still worked.
