### ISSUE TITLE
hashivault_write can't be used anymore to have csr/private key generated and crt signed

### ISSUE THREAD

**Issue by mirwan** [TerryHowe/ansible-modules-hashivault#179]
This is kind of a followup to #162. 
Since #135, I can't use `hashivault_write` to write to pki/intermediate/generate/exported or pki/root/sign-intermediate.
In my use-case, the first one is supposed to return csr and private key, the second is supposed to return a certificate (intermediate CA here) from csr (supposedly returned in the previous step).
Now that `no_log` is set to "true", csr and private key contain "********", sign-intermediate fails and/or check crt verification against priviate key fails.

**Comment by TerryHowe** [comment]
We might need a work around for this because https://github.com/ansible/ansible/issues/19278#issuecomment-266782201
