### ISSUE TITLE
Difficulty creating external groups with hashivault_identity_group

### ISSUE THREAD

**Issue by dorees** [TerryHowe/ansible-modules-hashivault#183]
Hi,

I'm trying to utilise external groups to implement multi-tenancy namespaces as shown in the Additional discussion of this Vault learning doc.
https://learn.hashicorp.com/vault/operations/namespaces#additional-discussion
The basic steps are to create an external group then attach an alias to link my LDAP authentication backend. 

Playbook
```---
- hosts: localhost
  gather_facts: no
  tasks:
    - hashivault_identity_group:
        name: ansible-group
        group_type: external
```

Output
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authtype": "token",
            "ca_cert": "",
            "ca_path": "",
            "client_cert": "",
            "client_key": "",
            "group_type": "external",
            "id": null,
            "member_entity_ids": [],
            "member_group_ids": [],
            "metadata": {},
            "mount_point": "identity",
            "name": "ansible-group",
            "namespace": null,
            "password": "",
            "policies": [],
            "role_id": "",
            "secret_id": "",
            "state": "present",
            "token": "removed",
            "url": "removed",
            "username": "",
            "verify": false
        }
    },
    "msg": "Exception: member entities can't be set manually for external groups",
    "rc": 1
}
```

I've noticed the docs specify that member_entity_ids and member_group_ids default to None but are output as empty lists. Am I missing something?

Any help is appreciated,

Dan

**Comment by TerryHowe** [comment]
The are definitely defaulting to empty list https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_identity_group.py#L121 

Any chance you could change that line and the one after to None and see if that resolves the problem?

**Comment by dorees** [comment]
I've rebuilt the module with the None default but get the same issue.

I believe the hvac code is looking for a None type, which I guess is different to the null output in Ansible?
https://github.com/hvac/hvac/blob/master/hvac/api/secrets_engines/identity.py#L516

`fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "authtype": "token",
            "ca_cert": "",
            "ca_path": "",
            "client_cert": "",
            "client_key": "",
            "group_type": "external",
            "id": null,
            "member_entity_ids": null,
            "member_group_ids": null,
            "metadata": {},
            "mount_point": "identity",
            "name": "ansible-group",
            "namespace": null,
            "password": "",
            "policies": [],
            "role_id": "",
            "secret_id": "",
            "state": "present",
            "token": "removed",
            "url": "removed",
            "username": "",
            "verify": false
        }
    },
    "msg": "Exception: member entities can't be set manually for external groups",
    "rc": 1
}`

**Comment by GuillaumeRemyCSI** [comment]
This issue is not solved yet, and I face this similar problem with external groups. I tend to think the problem comes from the underlying hvac library...

**Comment by GuillaumeRemyCSI** [comment]
I solved the issue and proposed a merge request to the hvac project. It was indeed an issue with the way the Vault API is called: https://github.com/hvac/hvac/pull/553

**Comment by GuillaumeRemyCSI** [comment]
This issue is also linked to #196, it is ready to be merged

**Comment by TerryHowe** [comment]
Both PRs have merged so this *should* be resolved.
