### ISSUE TITLE
Module to write to Hashicorp Vault - Documentation

### ISSUE THREAD

**Issue by rjsbsamarathunga** [TerryHowe/ansible-modules-hashivault#184]
Could you update the documentation to include an example for hashivault_write for following:
 `vault write aws/roles/ops policy=@policy.json`

or provide me a link to where it exists in the documentation (if it already does)?

As far as I can see, the documentation as of now only provides an example for secret write.

**Comment by rjsbsamarathunga** [comment]
or something like:
`vault write pki/root/generate/internal common_name=xyz.com`

**Comment by TerryHowe** [comment]
It kind of sounds like you are looking for https://terryhowe.github.io/ansible-modules-hashivault/modules/hashivault_write_from_file_module.html#hashivault-write-from-file-module
