### ISSUE TITLE
How use lookup plugin for kv-v2

### ISSUE THREAD

**Issue by ihard** [TerryHowe/ansible-modules-hashivault#192]
How use lookup plugin for kv-v2 secret engine, can I see a working example of using the plugin?
`{{ lookup('hashivault', 'secret/my', 'token', 'version=2') }}`
does not work

**Comment by astronaut808** [comment]
+1

I also tried, I could only read the secret 'token' from KVv2 'test-kv-v2' like this:
`- name: read secret
  set_fact:
    result: "{{lookup('hashivault', '/test-kv-v2/data/test-secret', '')}}"

- name: debug
  debug:
    msg: "{{ result.data.token }}"`

**Comment by ihard** [comment]
it looks like there is a rollback to the built in plugin hashi_vault as specified in the readme, but I put a package from pip3
Ansible 2.9.4
MacOS 10.15.3
Python3 from Xcode

**Comment by TerryHowe** [comment]
Hmm, missed this conversation, sorry. This should work

`looky_kv2: "{{lookup('hashivault', 'kv2/name', 'value', version=2)}}"`

From this test https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/functional/test_kv2.yml#L71
