### ISSUE TITLE
from ansible.module_utils.basic import AnsibleModule

### ISSUE THREAD

**Issue by JG127** [TerryHowe/ansible-modules-hashivault#193]
When running "python setup.py test". In PyCharm I'm getting the same error. 

Is there an additional setup required in order to run this project ?

**Comment by TerryHowe** [comment]
I had tox setup for testing, but I don't recall if the automated tests use that, so I don't completely guaranty it works at least the pep8 tests. The automated functional tests should pass.

**Comment by TerryHowe** [comment]
When I'm running `python setup.py test` I get a problem installing ansible requirements unrelated to this project.

**Comment by TerryHowe** [comment]
tox runs fine for the functional tests for me, but fails for pep8 which maybe should be fixed. I'm not entirely convinced pep8 should be a hard requirement here.

**Comment by TerryHowe** [comment]
Let me know if this is still an issue.
