### ISSUE TITLE
Feature Request: Enable and Configure Secret Backends

### ISSUE THREAD

**Issue by theonewolf** [TerryHowe/ansible-modules-hashivault#2]
There seems to be an API for enabling and configuring auth and audit backends, but not for secret backends.

Is this a feature that is planned for ansible-modules-hashivault?  This would help complete the automation of Vault setup.

**Comment by TerryHowe** [comment]
I don't have a specific plan to do that, but sounds like a good idea.   I'm using consul, but it is configured in the hcl.  In another instance, I'm using zookeeper, but again in the hcl.

**Comment by theonewolf** [comment]
Oh maybe it's already possible with your module, I was talking about `mount`ing things such as PKI:

https://www.vaultproject.io/docs/secrets/

Is that already supported somehow?  We were writing playbooks with your module and weren't sure how to mount PKI, or transit.

**Comment by TerryHowe** [comment]
It isn't there, it would very similar to hashivault_auth_enable, but calling the enable secret backend https://github.com/ianunruh/hvac/blob/master/hvac/v1/__init__.py#L263

**Comment by TerryHowe** [comment]
@theonewolf give 2.6.0 a shot, I just uploaded it.  If there any design issues etc, get back to me.

**Comment by theonewolf** [comment]
Oh thank you, we started using this feature @TerryHowe!  I think we are just working around (with CLI via Ansible) configuring PKI now (like creating a root CA etc.), which could be done through a more generic `hashivault_write`.  But I think the current one assumes `secret` as the backend.

**Comment by TerryHowe** [comment]
I made a change in 2.8.0 to hashivault_read and hashivault_write to support different mount points. 

https://github.com/TerryHowe/ansible-modules-hashivault/commit/904e31a68965034f95d5091d1178eec84850a83e

Probably doesn't change your situation exactly, but just for completeness of this conversation.

**Comment by theonewolf** [comment]
Oh @TerryHowe I think this is practically an exact match for what we needed.  We haven't tested that yet, but I think this would work well.

Obviously, we could make special functions to configure different backends, but I'd be satisfied with this more raw approach at first.  If you want, feel free to close this issue.  Deeper configuration would probably need a milestone + several issues I think.
