### ISSUE TITLE
hashivault_identity_entity causes "'NoneType'' object is not iterable" when entity has no policy

### ISSUE THREAD

**Issue by phihos** [TerryHowe/ansible-modules-hashivault#204]
When using the `hashivault_identity_entity` module on a preexisting entity that has no policy (not even default) attached to it the tasks fails with:
```
msg: 'Exception: ''NoneType'' object is not iterable'
```
The cause is this piece of code:
```python
def hashivault_identity_entity_update(entity_details, client, entity_id, entity_name, entity_metadata, entity_disabled, entity_policies):
# ...
  if entity_details['name'] != entity_name or entity_details['disabled'] != entity_disabled or \
       entity_details['metadata'] != entity_metadata or set(entity_details['policies']) != set(entity_policies):
  # ...
```
The  `set(entity_details['policies'])` causes the error, because `None` can not be converted into a `set`.

PR coming soon.

**Comment by TerryHowe** [comment]
This all sounds familiar this wasn't fixed in other PR was it we still have
some stuff that hasn't been released
