### ISSUE TITLE
Probable issue with response from vault api

### ISSUE THREAD

**Issue by HammerZ3it** [TerryHowe/ansible-modules-hashivault#212]
Hi there,

I think that there is maybe a problem with how the code handle the response from Vault API.
I am making a write into my vault from ansible and I get an error : 
`TypeError: Value of unknown type: <class 'requests.models.Response'>, <Response [204]>`

When I make a call for the secret I write, it is here (from ui or api).
But the ansible goes on an error (one mentioned earlier).

From the vault documentation : 

> Note: Applications should be prepared to accept both 200 and 204 as success. 204 is simply an indication that there is no response body to parse, but API endpoints that indicate that they return a 204 may return a 200 if warnings are generated during the operation.

**Comment by TerryHowe** [comment]
`hvac` is highly variable on what it returns at times. What module were you using hashivault_write? I'd be surprised if it was, but that seems to be what you are indicating. A little code snippet maybe?

**Comment by calvin15** [comment]
We had the same issue, apparently there is an issue in hvac 0.10.1, downgrading to 0.10.0 made it work again.

**Comment by TerryHowe** [comment]
Yeh, I'm seeing that too :facepalm:

**Comment by TerryHowe** [comment]
Not terribly happy with that fix, but it does work. I'll probably merge that soon, so if any comments, do it fast, thanks

**Comment by TerryHowe** [comment]
Fixed for 4.3.0

**Comment by HammerZ3it** [comment]
Thx @TerryHowe , sorry for the late answer ;).

Regards,
