### ISSUE TITLE
enable_audit_device uses name parameter as device_type in hvac

### ISSUE THREAD

**Issue by JoostvdB94** [TerryHowe/ansible-modules-hashivault#218]
The module `hashivault_audit_enable` uses the `name`-parameter for both `device_type` as well as the `path` variable to call the hvac method [`enable_audit_device`](https://hvac.readthedocs.io/en/stable/usage/system_backend/audit.html#enable-audit-device). 

The parameter `name` does not describe this behaviour. Besides, a person may want to name it's audit log to describe it's use. The `name` parameter description fits the the url mountpoint, but in my opinion not suitable for the `device_type` parameter in `hvac`

**Comment by TerryHowe** [comment]
Fixed in 4.4.0 but that module has been deprecated in favor of `hashivault_audit`
