### ISSUE TITLE
Path specified without '/' produces error "Path already in use"

### ISSUE THREAD

**Issue by JoostvdB94** [TerryHowe/ansible-modules-hashivault#221]
The check for the existance of an audit device will not succeed if an path is specified that does not end with a forward slash. When the path does not already exist, the creation of the audit device is successful. 
https://github.com/TerryHowe/ansible-modules-hashivault/blob/269b2135bba9d7a7638f37c2876046ed741a8a37/ansible/modules/hashivault/hashivault_audit.py#L120

To combat this issue, the `path` parameter should do any of the following: 
- check for the slash, and fail accordingly
- append a slash to the path if it does not end with a slash.
- append a slash where the path is checked (see referenced code line)

**Comment by TerryHowe** [comment]
4.4.2
