### ISSUE TITLE
Useless check and potentially broken check 

### ISSUE THREAD

**Issue by DrMagPie** [TerryHowe/ansible-modules-hashivault#229]
Hi,

I have noticed that in a lot of modules you have following check to strop tailing slash
https://github.com/TerryHowe/ansible-modules-hashivault/blob/c0a9843a0534885b03ba40c63e8941ba6888a5be/ansible/modules/hashivault/hashivault_k8s_auth_role.py#L99-L100

it seams completely useless, because that if always evaluates True.
And possibly there is no need to perform such checks at all.
 `The strip() method returns a copy of the string in which all chars have been stripped from the beginning and the end of the string (default whitespace characters).`

And also this looks like in following place check is miss used:
https://github.com/TerryHowe/ansible-modules-hashivault/blob/c0a9843a0534885b03ba40c63e8941ba6888a5be/ansible/modules/hashivault/hashivault_k8s_auth_config.py#L77
if we compare it with:
https://github.com/TerryHowe/ansible-modules-hashivault/blob/c0a9843a0534885b03ba40c63e8941ba6888a5be/ansible/modules/hashivault/hashivault_azure_auth_role.py#L144

these try/catch blocks are almost identical but k8s one is missing `...()['data'].keys():`

**Comment by TerryHowe** [comment]
It looks like the valid auths are passed at both levels, so either way works, it is just that other data is also passed at the top level (although none of them end in "/").

**Comment by TerryHowe** [comment]
I'm working on another PR for the list_auth_methods issue
