### ISSUE TITLE
Don't use list to validate existence

### ISSUE THREAD

**Issue by jamielennox** [TerryHowe/ansible-modules-hashivault#244]
This is biting in a number of places, but most recently: https://github.com/TerryHowe/ansible-modules-hashivault/blob/c97a39260162aa5dd8a5bbb4e05d10098f0f0a19/ansible/modules/hashivault/hashivault_k8s_auth_role.py#L104-L113 

Please let's not use in list to validate that something exists. It means that the automation tool I'm using now need to have `read` and `list` on `sys/auth` which given we're using the open source version (no namespaces) is more than my devops team wants to allow for this tool. 

To check existence lets just try and read the object, it's fair to think if i have write of that object I also have read of the same path.

**Comment by TerryHowe** [comment]
Okay, I see your point on that.

**Comment by TerryHowe** [comment]
I think cutting a release in a couple days would be good, so comment away on that PR if you see problems or that wasn't what you were thinking.

**Comment by jamielennox** [comment]
I left a comment just on a nit i saw. I haven't had a chance to test yet, but yea, it looks like what i was thinking. 

Thanks for doing this. I do mean to follow up these bugs with a PR if they sit there for a little while, but i appreciate you taking them on more quickly.

**Comment by jamielennox** [comment]
Related, or i can open a new bug: 
```
$ grep -R "mount_point" . | grep " in "
./hashivault_consul_secret_engine_role.py:    if (mount_point + "/") not in client.sys.list_mounted_secrets_engines()['data']:
./_hashivault_aws_ec2_role_create.py:    if (mount_point + "/") not in backends:
./hashivault_consul_secret_engine_config.py:    if (mount_point + "/") not in client.sys.list_mounted_secrets_engines()['data']:
./hashivault_auth_method.py:        if (mount_point + u"/") in auth_methods:
```
`./hashivault_auth_method.py` being the one most likely hit.

**Comment by TerryHowe** [comment]
`_hashivault_aws_ec2_role_create` is deprecated, I think I decided not to mess with it.

`hashivault_auth_method` I think is correct, if you can't read the backends, you can't create/delete one.

The consul ones I must of missed.
