### ISSUE TITLE
Import Vault intermediate certificate signed by Vault root CA

### ISSUE THREAD

**Issue by tomasodehnal** [TerryHowe/ansible-modules-hashivault#262]
Hello,

I'm starting with Vault in Ansible and ran into this awesome module. Thanks for all the effort.

I'm trying to set up root and intermediate CA in Vault using the module and found out I'm unable to import the signed intermediate CA cert. The module hashivault_pki_ca_set mentions:
_Not needed if you are generating a self-signed root certificate, and not used if you have a signed intermediate CA certificate with a generated key (use the /pki/intermediate/set-signed endpoint for that). If you have already set a certificate and key, they will be overridden._

Am I supposed to call that outside of the module, using curl for example?

Thanks in advance.

**Comment by TerryHowe** [comment]
Hmm, looks like that was just copied from the vault docs. That should read use hashivault_pki_set_signed which calls the hvac method that talks to that endpoint

**Comment by tomasodehnal** [comment]
I somehow missed that one. Thank you for the quick response.
