### ISSUE TITLE
hashivault_approle_role_create token type parameter missing

### ISSUE THREAD

**Issue by ashwinkupatkar** [TerryHowe/ansible-modules-hashivault#264]
Hi,

If i want to configure approle to generate batch tokens or periodic tokens on demand . 

I do not see a provision for the same

**Comment by TerryHowe** [comment]
You probably want to use some other approle module, that was is deprecated.

https://terryhowe.github.io/ansible-modules-hashivault/modules/list_of_hashivault_modules.html
