### ISSUE TITLE
hashivault_read_to_file module should pass all the common file params to the underlying copy module

### ISSUE THREAD

**Issue by drawks** [TerryHowe/ansible-modules-hashivault#273]
Like the rest of the modules which use ansible's underlying file module `hashivault_read_to_file` should accept the common set of file module parameters such as `owner`, `group`, setype`, etc.

Looking at the code and the log results it isclear that this module is calling the ansible copy module internally, but is being overzealous about parameter validation.

**Comment by TerryHowe** [comment]
Closed by https://github.com/TerryHowe/ansible-modules-hashivault/pull/285 I should have added this issue to the PR. It will pass all arguments, but rather than figure out which ones make sense and which don't, I just put them all in there. Some probably won't work.
