### ISSUE TITLE
vault root login and vault secrets enable

### ISSUE THREAD

**Issue by gowthamakanthan** [TerryHowe/ansible-modules-hashivault#291]
Team,

 Am using the following commands to do the initial login with root key (after the vault initiation), is there a way to do through ansible? 

Command: 
```
1. /usr/local/bin/vault login "{{ vault_root_token }}"
```
Tried ```hashivault_generate_root_init```,. Not sure whether am using the right modules. Any suggestions?

**Comment by TerryHowe** [comment]
Doesn't that just auth for a session? You shouldn't need to do that, just set the token in the environment variable `VAULT_TOKEN`.

See https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/README.rst
