### ISSUE TITLE
Cannot read from custom secret engine

### ISSUE THREAD

**Issue by zen** [TerryHowe/ansible-modules-hashivault#292]
Hi there Terrry,

Great job with the modules

I have one problem thou. I'm using multiple custom secret engines in Vault, for example: infrastructure of type kv2.
The structure is as follows:
infrastructure -> test_dir/infra_test -> test_infra : infra_value

I'm configuring the `hashivault_read` as follows:

```
    - name: Vault test inline infra
      hashivault_read:
        secret: test_dir/infra_test
        mount_point: /infrastructure
        key: test_infra
      register: vault_read_infra
    - debug:
        var: vault_read_infra.value
```

And getting following error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Secret /infrastructure/test_dir/infra_test is not in vault", "rc": 1}
```

While:
```
# vault kv get /infrastructure/test_dir/infra_test
====== Metadata ======
Key              Value
---              -----
created_time     2020-10-23T20:35:04.244874411Z
deletion_time    n/a
destroyed        false
version          2

======= Data =======
Key           Value
---           -----
test_infra    infra_value
```

Is KV2 engine supported?

**Comment by TerryHowe** [comment]
Yes, with `version: 2`

**Comment by zen** [comment]
Great, that worked without problems.
I added small PR with this mentioned in the docs
-> #293
