### ISSUE TITLE
init returns a dictionary with a key "keys" which is python internal method

### ISSUE THREAD

**Issue by jnsaff** [TerryHowe/ansible-modules-hashivault#30]
hashivault_init retuns a result that looks like this

`ok: [host] => {
    "msg": {
        "changed": true, 
        "keys": [
            "x", 
            "x", 
            "x", 
            "x", 
            "x"
        ], 
        "keys_base64": [
            "x", 
            "x", 
            "x", 
            "x", 
            "x"
        ], 
        "rc": 0, 
        "root_token": "x"
    }
}`

Now when I try to store these keys to a safe storage (credstash in my case) I am iterating over this structure

`- name: store unseal keys to credstash
  command: credstash put unseal-{{ item.0 }} {{ item.1 }}
  with_items: "{{ init_result.keys }}"`

I get an error as keys is a python internal method.

For keys_base64 everything works as expected.

Would you consider renaming "keys" to something that would not cause this issue?

**Comment by jnsaff** [comment]
Never mind {{ init_result['keys'] }} works, but I will leave this here just fyi.

**Comment by TerryHowe** [comment]
yeh, hindsight, maybe not that best name, but kind of tough to change now for people.
