### ISSUE TITLE
Overwriting an OIDC Role does not work

### ISSUE THREAD

**Issue by MaWiPPI** [TerryHowe/ansible-modules-hashivault#316]
Steps to reproduce:
1. Enable OIDC as an Auth-Method
2. Use "hashivault_oidc_auth_role" to set a config, for instance "allowed_redirect_uris"
3. Try to change this value to a different value

Expected behavior: Vault now has the new Value in Store
Actual behavior: Vault still uses the old configuration

This also results in multiple runs of the module always saying "changed=true".

I reproduced this on an Ubuntu 20.04 within WSL2, with a local Vault version 1.5.5 running Dev-Mode.

Workaround: Changing the state to "absent" and then to "present" fixes the problem

**Comment by TerryHowe** [comment]
So if changed is true, it must either hit:
https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_oidc_auth_role.py#L194
or
https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_oidc_auth_role.py#L198

and it should really be a matter of does this also do an update
https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_oidc_auth_role.py#L203

**Comment by vraimonds** [comment]
Encountering the same issue here.

**Comment by TerryHowe** [comment]
Reopen if this is still an issue
