### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by Vortelf** [TerryHowe/ansible-modules-hashivault#322]
Hello,

I just rebuild one of my automation images and after the update the AppRoles didn't have policies.
Finally fixed it by changing `policies` to `token_policies` after 4 hours of debugging.

Please update the documentation to be up-to-date with all the functionality covered by the module and please start writing changelog on the releases.

**Comment by TerryHowe** [comment]
I don't recall now if the change was in hvac or Hashicorp vault where this got changed from `policies` to `token_policies`. At this point, `policies` should be removed as a valid argument, we don't need backward compatibility for ever.

**Comment by TerryHowe** [comment]
Fixed
