### ISSUE TITLE
When behind nginx proxy, vault https url is wrongly constructed

### ISSUE THREAD

**Issue by chetanagrawal** [TerryHowe/ansible-modules-hashivault#33]
We have vault configured at /vault/ uri behind nginx proxy. So all our vault urls are https://localhost/vault/v1... likewise. Ngnix is configured to forward the request to http://localhost:8200/.

However, while using following module the resulting url is constructed as https://localhost/v1/sys/init and failing with 404 error. Ideally it should be https://localhost/vault/v1/sys/init. This is due to urljoin function in /usr/lib/python2.7/site-packages/hvac/v1/__init__.py

  hashivault_init:
    url: 'https://localhost/vault/'
    secret_shares: 1
    secret_threshold: 1
    verify: False
  register: init_status

**Comment by TerryHowe** [comment]
As long as you have the trailing slash, I *think* it should work.  The only potential problem I see is in the lookup plugin where it strips the trailing /

**Comment by chetanagrawal** [comment]
@TerryHowe , it does not work with trailing / either. It always strips /vault/

**Comment by TerryHowe** [comment]
I'm not sure what would be causing the problem.  The hashivault_init module calls hashivault_client and the url treatment is:

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/module_utils/hashivault.py#L30

and 

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/module_utils/hashivault.py#L46

I don't see anything in hvac either that would strip the trailing /

**Comment by chetanagrawal** [comment]
Its urljoin function in hvac module which recreates url removing /vault/

**Comment by TerryHowe** [comment]
```
import urlparse
urlparse.urljoin('http://localhost/vault/', 'v1/sys/init')
'http://localhost/vault/v1/sys/init'
```
not for me (with trailing slash).

**Comment by chetanagrawal** [comment]
I think in module its /v1/sys/init. Can you  try
urlparse.urljoin('http://localhost/vault/', '/v1/sys/init')

On 05-Oct-2017 12:29 AM, "Terry Howe" <notifications@github.com> wrote:

import urlparse
urlparse.urljoin('http://localhost/vault/', 'v1/sys/init')
'http://localhost/vault/v1/sys/init'

not for me (with trailing slash).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TerryHowe/ansible-modules-hashivault/issues/33#issuecomment-334256664>,
or mute the thread

**Comment by TerryHowe** [comment]
Yes, you are right.  Nothing I can do about it though, you'd need to take that up with hvac or change your proxy.  https://github.com/ianunruh/hvac/
