### ISSUE TITLE
Feature request for hashivault_auth_ldap module

### ISSUE THREAD

**Issue by tp6783** [TerryHowe/ansible-modules-hashivault#337]
Hello.

I am using the python wrappers you created in ansible scripts to confire vault as needed. In the setup I use LDAP as authentication method, for that I am using the hashivault_auth_ldap module.

This module supports a lot of configuration items as is shown in the [documentation](https://terryhowe.github.io/ansible-modules-hashivault/modules/hashivault_auth_ldap_module.html#hashivault-auth-ldap-module) of this project. But there are settings regarding LDAP authenticaton mentioned in the [vault documentation](https://www.vaultproject.io/api-docs/auth/ldap) which are not part of the hashivault_auth_ldap_module wrapper.

Two settings I need which are currently not supported are:
* token_ttl
* token_max_ttl.

Could you add support for these two settings in the hashivault_auth_ldap module.

**Comment by TerryHowe** [comment]
It would be fairly easy to add those to the module in a PR if you have a moment. Unfortunately, I'm way behind on life in general right now.

**Comment by TerryHowe** [comment]
Closed by f3b5f90d896493d8588d5f55e3cdbafb166c1ca5

**Comment by aderixon** [comment]
(Relevant commit actually appears to be 73abfc4)

Unfortunately, the type mismatch between the returned integer values for token_ttl and token_max_ttl and the specified string values causes this module to always return a 'changed' status even when the parameters are the same.

A basic fix would be to convert the returned current_state values to strings and use '0' for the desired_state defaults, e.g.:  
`current_state['token_ttl'] = str(result['token_ttl'])`  
But that would fail when the ttl is set to a string value such as '24h', as the returned current_state value would be '86400'. Not sure how this could be addressed.
