### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by erinn** [TerryHowe/ansible-modules-hashivault#351]
It looks like the last tagged release was in November of 2020, curious if you can push out a new release? Personally I am looking for the provider_config option in OIDC which was merged in three months ago, but I'm sure there are other changes that folks might want in a full release.

Thanks,
-Erinn

**Comment by TerryHowe** [comment]
Yeh, sorry, I didn't realize it had been so long. Caught up in the `$DAY_JOB` I have made some progress lately and hopefully can get some more progress next week. Travis is broken, but tests are passing locally.

**Comment by TerryHowe** [comment]
Done. Thanks for the reminder.
