### ISSUE TITLE
Missing option to set token_type

### ISSUE THREAD

**Issue by alexbluhm** [TerryHowe/ansible-modules-hashivault#356]
https://github.com/TerryHowe/ansible-modules-hashivault/blob/3ee60619929722780179136924248303094641d4/ansible/modules/hashivault/hashivault_k8s_auth_role.py#L16
Would like to use this module to set k8s auth role token_type=batch, but that is not currently supported.

**Comment by TerryHowe** [comment]
Sounds reasonable. Fairly easy PR if you get around to it. Thanks
