### ISSUE TITLE
rekey does not seem to work

### ISSUE THREAD

**Issue by jeffrey-song-index** [TerryHowe/ansible-modules-hashivault#362]
Hi! The documentation on rekey is not so clear.
The example does this
`- hashivault_rekey:
      key: '{{vault_key}}'
      nonce: '{{nonce}}'`
But it says that it requires that a rekey be started with hashivault_rekey_init. What exactly does that mean?
Also, to perform rekey, we need that nonce. But hashivault_rekey_init does not return nonce if I am not mistaken.

Is this a bug, or am I missing something?

Thank you!

**Comment by TerryHowe** [comment]
I don't think there is a bug. It might help looking at the automated functional tests, sorry about the asserts:

https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/functional/test_rekey.yml
https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/functional/test_rekey_verify.yml

**Comment by jeffrey-song-index** [comment]
That's right. Thank you.

**Comment by TerryHowe** [comment]
Clarification https://github.com/TerryHowe/ansible-modules-hashivault/commit/72b431ec626c4af4235fd347c7d81e24b595822c
