### ISSUE TITLE
Rekey backup

### ISSUE THREAD

**Issue by jeffrey-song-index** [TerryHowe/ansible-modules-hashivault#363]
Hi! Does rekey init support backup? I did not find it in the documentation.

Thank you.

**Comment by TerryHowe** [comment]
Yes it does https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_rekey_init.py#L45 

Just missing from the docs generated out of this https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_rekey_init.py#L15
