### ISSUE TITLE
Use of approle as auth method

### ISSUE THREAD

**Issue by benemon** [TerryHowe/ansible-modules-hashivault#367]
When looking at [the pki cert issue module](https://terryhowe.github.io/ansible-modules-hashivault/modules/hashivault_pki_cert_issue_module.html) - and actually this probably extends to other modules - whilst `approle` is apparently a supported authentication method, I'm unclear how to provide the necessary roleId / secretId to allow the module to authenticate with an approle.

Should I be using other modules such as `_approle_role_id` to retrieve the role Id, and then one of the `_approle_secret` modules to generate a token?

Edit:
I suppose I'm just looking for what the functional equivalent of using approle in the `hashi_vault` lookup would be in the world of `ansible_modules_hashivault`.

```
"{{ lookup('hashi_vault', 'secret=kv/data/{{ vault_path }} auth_method=approle role_id={{ role_id }} secret_id={{ secret_id }} url={{ url }}  )}}"
```

**Comment by TerryHowe** [comment]
I would think that would work using approle, but off the top of my head I don't know what role needs to be used.

**Comment by TerryHowe** [comment]
This seems to be a general vault question rather than something specific to the module.

**Comment by benemon** [comment]
I'm sorry if I wasn't clear - its a question about how to use approle in
the context of the module you have created to authenticate against a vault
instance.

I'm well aware I can use an approle to do this. What I'm unclear on is how
/ if I can configure that module to use the role ID and secret ID, or if
there's an approach you'd recommend using some of your other modules to
generate a token using my approle roleID and secretID.
