### ISSUE TITLE
Possible to cut new release?

### ISSUE THREAD

**Issue by ventris** [TerryHowe/ansible-modules-hashivault#373]
Due to the changes in https://github.com/TerryHowe/ansible-modules-hashivault/pull/357 it would be awesome if you could cut a release for pypi so that users of the module are able to upgrade and remove the depreciation warning. As the last tag was created before the change was merged to main.

**Comment by TerryHowe** [comment]
https://pypi.org/project/ansible-modules-hashivault/4.6.5/
Thanks!
