### ISSUE TITLE
root_credentials_rotate_statements on connection_details map

### ISSUE THREAD

**Issue by Roxyrob** [TerryHowe/ansible-modules-hashivault#379]
Hi @TerryHowe,
I'm not sure if it is a bug or it works. Setting vault database/config using cli I see `root_credentials_rotate_statements` statement on its own configuration line:

<pre>
Key                                   Value
---                                   -----
allowed_roles                         [role1 role2]
connection_details                    map[connection_url:{{username}}:{{password}}@tcp(dbhost:3306)/ username:vault
password_policy                       n/a
plugin_name                           mysql-database-plugin
<b>root_credentials_rotate_statements    [SET PASSWORD = PASSWORD('{{password}}')]</b>
</pre>

Likewise, using module `hashivault_db_secret_engine_config` i see
* an **empty** `root_credentials_rotate_statements ` and **rotate statement appears inside connection_details** 
* **task changes on every ansible run also if no change was done in code**.
<br><br>
Do you know if it is a bug ? if so there is a workaround ?

<pre>
Key                                   Value
---                                   -----
allowed_roles                         [role1 role2]
connection_details                    map[connection_url:{{username}}:{{password}}@tcp(dbhost:3306)/ <b>root_credentials_rotate_statements [SET PASSWORD = PASSWORD({{password}})]</b> username:vault]
password_policy                       n/a
plugin_name                           mysql-database-plugin
<b>root_credentials_rotate_statements    []</b>
</pre>

**Comment by TerryHowe** [comment]
Not sure if it is a bug or not, but root_credentials_rotate_statements is defaulted to empty array. Maybe it was/is required?

https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_db_secret_engine_config.py#L85

Idempotent would be determined by this https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_db_secret_engine_config.py#L141

Looks kind of like the root_credentials_rotate_statements is showing up on your connection details in example two, but I'm not entirely sure what the input was to create example two.

**Comment by Roxyrob** [comment]
Hi @TerryHowe 
although this seems related to #381 it is not really. This issue is not related to idempotency but to the uncommon presence of root_credential_rotate_statements in `connection details map`  (I think is not correct) when I use hashivault module.

For MySQL version < 5.7 you need to specify `root_rotation_statements` as the default one will not work. So doing this using vaut cli like below:

<pre>
vault write database/config/mydbname \
  plugin_name=mysql-legacy-database-plugin \
  connection_url="{{username}}:{{password}}@tcp(db1.example.com:3306)/" \
  root_rotation_statements="SET PASSWORD = PASSWORD('{{password}}')" \
  allowed_roles="..." \
  username="vault" \
  password="..."
</pre>

will produce this configurration inside vault (that seems correct):

<pre>
...
<b>connection_details                    map[connection_url:{{username}}:{{password}}@tcp(dbhost:3306)/ username:vault</b>
password_policy                       n/a
plugin_name                           mysql-database-plugin
<b>root_credentials_rotate_statements    [SET PASSWORD = PASSWORD('{{password}}')]</b>
</pre>

Whereas the same configuration done using  hashivault module show below :

<pre>
- hashivault_db_secret_engine_config:
    mount_point: ...
    name: ,,,
    plugin_name: 'mysql-database-plugin'
    state: present
    root_credentials_rotate_statements: "SET PASSWORD = PASSWORD({{'{{password}}'}})"
    allowed_roles: "..."
    connection_details:
      username: "..."
      password: "..."
      connection_url: "..."
    verify_connection: false
</pre>

will create inside vault example two you can see in the initial post.

**Comment by Roxyrob** [comment]
Hi @TerryHowe 
about this:
> Not sure if it is a bug or not, but root_credentials_rotate_statements is defaulted to empty array. Maybe it was/is required?

AFAIK, for dynamic secret engine configuration vault support root credential rotation (but do not execute automatically as for static ones). It is logically correct that rotation be a process always changing status. I use this code to impose rotation (with additional when condition to force rotation with a boolean flag):

<pre>
- name: Vault database engine credentials rotation
  hashivault_write:
    token: "..."
    url: "..."
    mount_point: "/"
    version: 1
    secret: "database/rotate-root/myenginename"
  when: vault_creds_rotate_force|bool
</pre>

Rotation works well and change on every run for rotation is ok. The issue is on `hashivault_db_secret_engine_config` that always will change (as demostrated by sample code in #381 also when **nothing changes in code**) and so this process take place:

1. `hashivault_db_secret_engine_config` correctly config secret engine (user, "initial password", conneciton, ecc.)
2. `hashivault_write` as soon as flag is true will instruct vault to rotate db user password and set **new password** as internal vault db user password
3. At next run, also if nothing changes externally on vault config, `hashivault_db_secret_engine_config` that always changes configuration (**without respect for idempotency**) will change back also internal vault db usuer password (with **old password**), invalidating rotation and blocking automation

**Comment by TerryHowe** [comment]
Released as 4.6.6

**Comment by Roxyrob** [comment]
Release 4.6.6 worked.
After deleting database/config/... and running ansible code again no more rotate statement appears inside connection_details.

Thank you for fixing this issue
