### ISSUE TITLE
Secret Engine password rotation

### ISSUE THREAD

**Issue by Roxyrob** [TerryHowe/ansible-modules-hashivault#380]
I cannot figure out if there are ansible-module-hashicorp modules to allow arbitrary API write (POST) like that needed for root password rotation in dynamic secret engines (database, aws, ecc.) like these:
<pre>
<b>(cli - database)</b>
vault write -force database/rotate-root/name

<b>(api - database)</b>
curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST $VAULT_ADDR/v1/database/rotate-root/name

or

<b>(cli - aws)</b>
vault write -force aws/config/rotate-root

<b>(api - aws)</b>
curl --header "X-Vault-Token: $VAULT_TOKEN" --request POST $VAULT_ADDR/v1/aws/config/rotate-root
</pre>

Both `hashivault_write` and `hashivault_secret ` doesn't seem made to produce needed api call.

**Comment by Roxyrob** [comment]
I found a solution tested for database dynamic secret engine (probably will work with others too):

<pre>
- name: vault | Vault database engine credentials rotation
  hashivault_write:
    token: "..."
    url: "..."
    mount_point: "/"
    version: 1
    secret: "database/rotate-root/name"
</pre>

No luck with `hashivault_secret` as also defining `data` argument this module try to read (GET) instead of updare (POST).

**Comment by TerryHowe** [comment]
Ahh, thanks for that
