### ISSUE TITLE
Idempotency issue for hashivault_db_secret_engine_role

### ISSUE THREAD

**Issue by Roxyrob** [TerryHowe/ansible-modules-hashivault#383]
Hi @TerryHowe,
as for 'hashivault_db_secret_engine_config' (ref. #381) also module `hashivault_db_secret_engine_role` isn't idempotent.

Try to run multiple times `ansible-playbook` on below code , on every run you'll note tasks with ` hashivault_db_secret_engine_config` and `hashivault_db_secret_engine_role` signal a changes despite the fact that no changes take place in the code or on the vault itself:

note: set your connection_details like `username:`, `password:` and `connection_url`

<pre>
    - name: Enable database secrets engine
      hashivault_secret_engine:
        backend: 'database'
        name: 'testdbpath1'
        description: "Any description you want"
        state: 'enabled'
        config:
          default_lease_ttl: 180
          max_lease_ttl: 3600

    - name: Set vault database config
      hashivault_db_secret_engine_config:
        mount_point: 'testdbpath1'
        name: 'test-dbengine1'
        plugin_name: 'mssql-database-plugin'
        state: 'present'
        allowed_roles: "testrole1"
        connection_details:
          username: 'vaultusertest'
          password: 'YourSuperSecretPwd)'
          connection_url: "sqlserver://{{'{{username}}'}}:{{'{{password}}'}}@dbserver.example.com:1433"
      no_log: true

    - name: Set vault database role
      hashivault_db_secret_engine_role:
        name: 'testrole1'
        db_name: 'test-dbengine1'
        mount_point: 'testdbpath1'
        creation_statements: "select 'a' as A"
        revocation_statements: "select 'a' as B;"
        state: 'present'
        token_ttl: 120
        token_max_ttl: 1800
</pre>

This behavior means you cannot know about real changes an cannot use these modules to configure and manage hashicorp vault database secret engine with ansible.

Can you please solve these idempotency issues since we would like to use hashivault modules in our projects but such issues stop us ?

**Comment by TerryHowe** [comment]
My $DAY_JOB gets in the way of providing a super quick turn around on issues. I'd love to get these fixed, but priorities. I think on your other ticket I pointed out around where the problem is. If you get a chance, look at it and submit a PR. This is the open source world after all.

**Comment by Roxyrob** [comment]
Probably idempotency issue for this module was related to #384. Removing comma or fixing argument using list instead of string made the problem disappear.
