### ISSUE TITLE
Commas disappear using module hashivault_db_secret_engine_role

### ISSUE THREAD

**Issue by Roxyrob** [TerryHowe/ansible-modules-hashivault#384]
Hi @TerryHowe,
module `hashivault_db_secret_engine_role` has an issue with **`commas`**.
Any comma present in the task for arguments `creation_statements` and `creation_statements` (not tested on other arguments), will completely disappear on vault, leaving incomplete queries returning errors !

To reproduce the issue you can run `ansible-playbook` on below code:
     note: set your connection_details like `username:`, `password:` and `connection_url`
<pre>
    - name: Enable database secrets engine
      hashivault_secret_engine:
        backend: 'database'
        name: 'testdbpath1'
        description: "Any description you want"
        state: 'enabled'
        config:
          default_lease_ttl: 180
          max_lease_ttl: 3600

    - name: Set vault database config
      hashivault_db_secret_engine_config:
        mount_point: 'testdbpath1'
        name: 'test-dbengine1'
        plugin_name: 'mssql-database-plugin'
        state: 'present'
        allowed_roles: "testrole1"
        connection_details:
          username: 'vaultusertest'
          password: 'YourSuperSecretPwd)'
          connection_url: "sqlserver://{{'{{username}}'}}:{{'{{password}}'}}@dbserver.example.com:1433"
      no_log: true

    - name: Set vault database role
      hashivault_db_secret_engine_role:
        name: 'testrole1'
        db_name: 'test-dbengine1'
        mount_point: 'testdbpath1'
        creation_statements: "<b>CREATE LOGIN name WITH PASSWORD=password , DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;</b>"
        revocation_statements: "<b>select 'a' as A test commas: 1, 2, 3, 4, 5,  ,,, lastKEY;</b>"
        state: 'present'
        token_ttl: 120
        token_max_ttl: 1800
</pre>

then on vault run
<pre>
vault read testdbpath1/roles/testrole1

Key                      Value
---                      -----
creation_statements      [<b>CREATE LOGIN name WITH PASSWORD=password DEFAULT_DATABASE=[master] CHECK_EXPIRATION=OFF CHECK_POLICY=OFF;</b>]
db_name                  test-dbengine1
default_ttl              2m
max_ttl                  30m
renew_statements         []
revocation_statements    [<b>select 'a' as A test commas: 1 2 3 4 5 lastKEY;</b>]
rollback_statements      []

</pre>

you'll see that no commas was saved inside vault for `creation_statements` and `revocation_statements` fields.
This is a blocking issue too.

**Comment by ayav09** [comment]
This is due to the Ansible typecasting that the module performs as it expects a list and not a string for `creation_statements`, `revocation_statements`, `rollback_statements`, and `renew_statements`. This can be more easily seen in the output from curl.

```
curl --header "X-Vault-Token: ${VAULT_TOKEN}" http://127.0.0.1:8201/v1/testdbpath1/roles/tester | python3 -m json.tool

{
    "request_id": "d9a87674-72a4-bd06-4d73-1806ed086ed4",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 0,
    "data": {
        "creation_statements": [
            "select 'a' as A"
        ],
        "db_name": "test",
        "default_ttl": 120,
        "max_ttl": 1800,
        "renew_statements": [],
        "revocation_statements": [
            "select 'a' as A test commas: 1",
            "2",
            "3",
            "4",
            "5",
            "lastKEY;"
        ],
        "rollback_statements": []
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
}
```

**Comment by Roxyrob** [comment]
You are right @ayav09 it  works... I missed it.
Thank you

**Comment by TerryHowe** [comment]
Thanks I added this to maybe help others https://github.com/TerryHowe/ansible-modules-hashivault/commit/cb2fc582fc5e5a4ec65a595594206af408dc1a5c

**Comment by TerryHowe** [comment]
New release out with some related fixes

**Comment by Roxyrob** [comment]
Thanks for all the fixes !
