### ISSUE TITLE
Module not found after installation

### ISSUE THREAD

**Issue by pat-s** [TerryHowe/ansible-modules-hashivault#387]
Sorry for the potentially silly question but I need help with respect to installation.

I've used both ways outlined in the README to install the module.
I can see it in `~/.ansible/roles` yet my playbook is unable to detect the module for the use in a task.

```
ERROR! couldn't resolve module/action 'ansible-modules-hashivault.hashivault_read'. This often indicates a misspelling, missing collection, or incorrect module path.
```

(the same happens if I only use `hashivault_read`)

My ansible module path is default, i.e.

```
~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules',
```

Even when adding `~/.ansible/roles`, the module can't be found.

Which beginner mistake do I make here?

```
 /opt/homebrew/bin/ansible --version                                                                                                                              3s 23:27:26
ansible [core 2.12.2]
  config file = None
  configured module search path = ['/Users/pjs/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/pjs/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.10 (main, Jan 15 2022, 11:40:53) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.3
  libyaml = True
```

**Comment by TerryHowe** [comment]
On my mac, I always use a virtual environment and that seems to work fine. This may be similar to the issue on Linux when installing ansible with apt-get https://github.com/TerryHowe/ansible-modules-hashivault/issues/55 So, it isn't a solution to your problem necessarily, but a work around to use an venv

**Comment by pat-s** [comment]
Thanks. Helpful comments in the linked resources.

I re(?) installed via `pip` and now I got it working. I thought I tried this multiple times before opening this issue actually...

In my task yaml I can now specify

```yml
hashivault_read_to_file:
```

and I did not have to modify the ansible PATH to make it happen.
