### ISSUE TITLE
Replace python shebang with python3

### ISSUE THREAD

**Issue by PhotoTeeborChoka** [TerryHowe/ansible-modules-hashivault#416]
## What
Since the python 2 has been deprecated, Ubuntu OS does not ship the `/usr/bin/python` command. The shebang used in this project's files references it though, which leads to module failures on Ubuntu OS. In order to improve the expected behavior, the shebangs **should be replaced with `#!/usr/bin/env python3`.

**Comment by PhotoTeeborChoka** [comment]
This likely relates to issues in #415

**Comment by TerryHowe** [comment]
This comes off as more of an ubuntu problem. I don't think it makes sense to fix
