### ISSUE TITLE
`create_token` is deprecated for removal in hvac

### ISSUE THREAD

**Issue by bendem** [TerryHowe/ansible-modules-hashivault#418]
https://github.com/hvac/hvac/blob/7b94991e7c370756f1b2e4a7a4ffc602aea958ec/hvac/v1/__init__.py#L313-L317

**Comment by TerryHowe** [comment]
Thanks, looks like it is only currently used in ansible/modules/hashivault/hashivault_token_create.py

**Comment by TerryHowe** [comment]
Fixed
