### ISSUE TITLE
hashivault_init not work with seal type transit

### ISSUE THREAD

**Issue by ihard** [TerryHowe/ansible-modules-hashivault#428]
When I try to initialize Vault with transit auto-unseal I get an error
```
hvac.exceptions.InvalidRequest: parameters secret_shares,secret_threshold not applicable to seal type transit, on put http://127.0.0.1:8200/v1/sys/init
```
and I can’t skip it because the parameters are set by default and are always transmitted
```
secret_shares: omit
secret_threshold: omit
```
or
```
secret_shares: None
secret_threshold: None
```
not working

**Comment by TerryHowe** [comment]
Sounds like the kwargs would have to be constructed differently here since they are ints and defaulted:
https://github.com/TerryHowe/ansible-modules-hashivault/blob/main/ansible/modules/hashivault/hashivault_init.py#L98:L99

**Comment by DaazKu** [comment]
Similar problem with `seal "awskms"`: https://github.com/TerryHowe/ansible-modules-hashivault/issues/116#issuecomment-1896654342
