### ISSUE TITLE
Possible hvac breaking change

### ISSUE THREAD

**Issue by TerryHowe** [TerryHowe/ansible-modules-hashivault#431]
Running `ansible-playbook -v test_azure_auth_config.yml`

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'root_password_ttl'
```

**Comment by ceesios** [comment]
you could fix this by adding `if k in desired_state:` in the for loop. It prevents inconsistencies between the current and desired state to become a problem.
