### ISSUE TITLE
hashivault_secret_engine doesn't support seal wrap

### ISSUE THREAD

**Issue by emoryotott19** [TerryHowe/ansible-modules-hashivault#450]
hashivault_secret_engine doesn't support seal wrap enterprise feature. Will submit a PR to resolve. Confirmed I am not able to update the value with the 'config' or 'options' parameters, as this is a parameter outside of config and options

Example post body where seal wrap is activated:
{path: "kv", type: "kv", config: {}, options: {version: 2}, seal_wrap: true}

Documentation:
https://developer.hashicorp.com/vault/docs/enterprise/sealwrap

**Comment by TerryHowe** [comment]
A PR would be awesome, but looking at the commmit it would be better to avoid the ' to " change. Coming from another language I can see how that might be a thing, but I think ' is more pythonic

**Comment by emoryotott19** [comment]
@TerryHowe Running test very similar to what you have locally, and I am not running into the same issue. Wonder if it could be related to test suite not running enterprise vault.

I am using hvac 1.2.1 and version is vault-enterprise-1.12.0

- name: Enable kv2 secret store
  delegate_to: localhost
  tags:
    - test
  hashivault_secret_engine:
    name: kv2
    url: "{{ inventory_hostname }}"
    verify: false
    token: "{{ hostvars[inventory_hostname].root_token }}"
    namespace: "root"
    backend: kv
    seal_wrap: true
    options:
      version: 2
  register: 'vault_secret_enable'



changed: [server -> localhost] => {
"changed": true,
"created": true,
"diff": {
"after": {
"default_lease_ttl": 2764800,
"description": "",
"force_no_cache": false,
"max_lease_ttl": 2764800,
"options": {
"version": 2
}
},
"before": {}
},
"invocation": {
"module_args": {
"authtype": "token",
"aws_header": null,
"backend": "kv",
"ca_cert": "",
"ca_path": "",
"cas_required": null,
"client_cert": "",
"client_key": "",
"config": {
"default_lease_ttl": 2764800,
"force_no_cache": false,
"max_lease_ttl": 2764800
},
"description": "",
"login_mount_point": null,
"max_versions": null,
"name": "kv2",
"namespace": "root",
"options": {
"version": 2
},
"password": null,
"role_id": null,
"seal_wrap": true,
"secret_id": null,
"state": "present",
"timeout": 30,
"token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"url": "server",
"username": "",
"verify": false
}
},
"rc": 0
}

**Comment by emoryotott19** [comment]
Merged to main
