### ISSUE TITLE
hashivault_write reports changes in "update" mode when passing strings for int values

### ISSUE THREAD

**Issue by adaphi** [TerryHowe/ansible-modules-hashivault#46]
Hey,

There are some places in the Vault API where you can write a string value, but reading returns an int value. For example, the max_ttl value inside a role in the SSH backend. Though the documentation example (https://www.vaultproject.io/api/secret/ssh/index.html#read-role) shows it returning a string, it actually returns a plain integer value:

```
curl -H "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/ssh/roles/testrole
{"request_id":"ed7b1f29-5f64-0016-9c09-3f214876b26c","lease_id":"","renewable":false,"lease_duration":0,"data":{"allow_bare_domains":false,"allow_host_certificates":false,"allow_subdomains":false,"allow_user_certificates":true,"allow_user_key_ids":false,"allowed_critical_options":"","allowed_domains":"","allowed_extensions":"","allowed_users":"*","default_critical_options":{},"default_extensions":{"permit-pty":""},"default_user":"centos","key_id_format":"","key_type":"ca","max_ttl":0,"ttl":1800},"wrap_info":null,"warnings":null,"auth":null}
```

The way the hashivault_write module checks for changes means that if you write a string value from Ansible, it will always be reported as a change, even though nothing has actually changed.

The obvious workaround is to set an integer value in Ansible instead, but this isn't always possible - for example, when the value is templated (as in our case) it will always be a string, and so will always be marked as changed.

Would it be possible to have the check relaxed slightly, so that the string value is not treated as a change?

It's worth mentioning that there are other cases in which you get a similar "always changed" behaviour due to reads not matching the writes, e.g. when using values like "30m" for a TTL value, which the read returns as "1800". I doubt that's so easily fixable though, as it depends on what field is being written/read, and there are inconsistencies between the backends (as some return "1800" and some return "30m0s")

**Comment by TerryHowe** [comment]
Sounds reasonable to me.  It'd be a while before I get to it, but feel free to submit a PR.

**Comment by TerryHowe** [comment]
Hopefully these test cases cover what you are talking about https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/functional/test_write.yml#L94
