### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by vsaveliev** [TerryHowe/ansible-modules-hashivault#48]
Hi.

It will be good if you add installation guide of your modules to ansible. Because it's not clear for not Python developers and for people who hasn't enough experience in Ops to do that. 

Thank you.

**Comment by TerryHowe** [comment]
I just updated the README is this enough: https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/README.rst

**Comment by TerryHowe** [comment]
I'm going to call that good enough, let me know if you were thinking something else, thanks!

**Comment by vsaveliev** [comment]
Yes, it's enough. Thank you.
