### ISSUE TITLE
hashivault_write always tries to read before writing, even when update=false

### ISSUE THREAD

**Issue by adaphi** [TerryHowe/ansible-modules-hashivault#50]
Hey,

As the title says. I can see this was changed recently but it actually breaks a number of things.

One example is the aws secret backend, which is configured at the path `aws/config/root`. But this path is write-only, so trying to read first throws an error.

Likewise for approles, you can generate a secret-id by writing to `auth/approle/role/my-role/secret-id`, but attempting to read from this path is an error.

It also fails if you simply don't have permission to read the endpoint you're trying to write to (entirely possible for automated scripts)

Can you revert the change please? Or find a way of doing the same that doesn't error in these cases?

**Comment by TerryHowe** [comment]
Almost sounds like two issues there, it kind of sounds like there is at least a missing approle test, correct?  People keep coming in with PRs to read before write and I finally gave in.  That can be corrected.

**Comment by TerryHowe** [comment]
Release 3.8.6 should address your issue, but I still feel there is a test missing for approle somehow.

**Comment by adaphi** [comment]
Thanks for the change. I hadn't actually looked at the tests, but I guess the difference there is that we're still using hashivault_write to get a secret-id, whereas the tests are using hashivault_approle_role_secret_create. We probably need to update our code to use the newer call.
