### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by mohsen0** [TerryHowe/ansible-modules-hashivault#53]
Do you publish a changelog for this nice module somewhere else? it is not easy to keep up with the changes if one had to look at the commits

**Comment by TerryHowe** [comment]
Sorry, I should but do not.  I'll get something going.

Only recent change was for hashivault_get_policy to return an error if the policy does not exist.

**Comment by TerryHowe** [comment]
Updated https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/CHANGELOG.rst and created procedure with gitchangelog to keep it up to date.
