### ISSUE TITLE
Module fails to unseal

### ISSUE THREAD

**Issue by bru2code** [TerryHowe/ansible-modules-hashivault#57]
- hosts: localhost
  vars:
    vault_keys:  "{{ lookup('env','VAULT_KEY1', 'VAULT_KEY2', 'VAULT_KEY3') }}"
  tasks:
    - name: print environment
      debug:
        msg: "key vaule{{item}}"
      with_items:
        - "{{ vault_keys }}"

    - name: Unseal status
      hashivault_status:
      register: 'vault_status'

    - name: Print the status of vault
      debug:
        msg: "vault environment sealed ? {{ vault_status.status.sealed }}"

    - name: Unseal Vault if Sealed
      hashivault_unseal:
        keys: '{{vault_keys}}'
      when: vault_status.status.sealed == True

I had to set vault keys separately on bash, and even then it fails to unseal with below error 

TASK [print environment] ********************************************************************************************************************************************************************************************************************
Friday 30 March 2018  11:34:54 +0100 (0:00:00.539)       0:00:00.618 **********
ok: [localhost] => (item=RExlyUib/KhCRCHHWpLc0+CGFlrrk2gFM0FaKc4C7IrH,uIFpZScsRF74+SISdPe+icR1g1yP3P2p9z/Nh/fP9Mkm,KHw8ph30CmNF5Bh0AyBiVIZ6M8lVXKzPkFLnOUbS8wVQ) => {
    "item": "RExlyUib/KhCRCHHWpLc0+CGFlrrk2gFM0FaKc4C7IrH,uIFpZScsRF74+SISdPe+icR1g1yP3P2p9z/Nh/fP9Mkm,KHw8ph30CmNF5Bh0AyBiVIZ6M8lVXKzPkFLnOUbS8wVQ",
    "msg": "key vauleRExlyUib/KhCRCHHWpLc0+CGFlrrk2gFM0FaKc4C7IrH,uIFpZScsRF74+SISdPe+icR1g1yP3P2p9z/Nh/fP9Mkm,KHw8ph30CmNF5Bh0AyBiVIZ6M8lVXKzPkFLnOUbS8wVQ"
}

TASK [Unseal status] ************************************************************************************************************************************************************************************************************************
Friday 30 March 2018  11:34:54 +0100 (0:00:00.028)       0:00:00.647 **********
ok: [localhost]

TASK [Print the status of vault] ************************************************************************************************************************************************************************************************************
Friday 30 March 2018  11:34:54 +0100 (0:00:00.420)       0:00:01.067 **********
ok: [localhost] => {
    "msg": "vault environment sealed ? True"
}

TASK [Unseal Vault if Sealed] ***************************************************************************************************************************************************************************************************************
Friday 30 March 2018  11:34:54 +0100 (0:00:00.035)       0:00:01.103 **********
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Exception: 'key' must be a valid hex or base64 string", "rc": 1}
 [WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (</usr/lib/python2.7/site-packages/ansible/plugins/callback/mail.CallbackModule object at 0x1927ed0>): 'module_name'

**Comment by TerryHowe** [comment]
Unseal expects keys separated by a space and you are using commas

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_unseal.py#L83

I'd recommend storing the keys in a single environment variable and joining them on init like the functional tests:

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/functional/test_init.yml#L18
