### ISSUE TITLE
hashivault_secret_enable to enable with type

### ISSUE THREAD

**Issue by bru2code** [TerryHowe/ansible-modules-hashivault#58]
Hi,

I am trying to use hashivault_secret_enable to enable ssh-backend, something similar to below. And I don't see any equivalent options in the py. Do you know if there is a quick way to do this perhaps! 
```
vault secrets enable -path=ssh-prod ssh 
```
Cheers, Raj

**Comment by TerryHowe** [comment]
That should be something like:
```
    - hashivault_secret_enable:
        name: "ssh-pro"
        backend: "ssh"
```

**Comment by TerryHowe** [comment]
I have to assume this is resolved
