### ISSUE TITLE
Missing EC2 auth support

### ISSUE THREAD

**Issue by TerryHowe** [TerryHowe/ansible-modules-hashivault#61]

**Comment by simonmacklin** [comment]
I would like to tackle this issue but not sure how I could write any automated functional tests for it.  I can test this manually but wouldn't be able to include any tests in the CI part.  

I wondered if there is anyway we could use the python mocking libraries in anyway? 

Any suggestions?

**Comment by TerryHowe** [comment]
I think it will be too much effort to write an automated functional test for this.

**Comment by simonmacklin** [comment]
That's fair enough. 

Many thanks

**Comment by simonmacklin** [comment]
Hey @TerryHowe 

I have made a small start on the IAM auth.  The methods work but I don't seem to get the token within the client object.  I know 100% a token is being returned but for some reason its not ending up in the client object passed into the "hashivault_auth" method.  I just get a empty token value.  

Its late in the UK so I might just be missing something silly but wondered if you get a moment to have a quick look.  

Hear is the branch 
https://github.com/simonmacklin/ansible-modules-hashivault/tree/feature-support_iam_role
https://github.com/simonmacklin/ansible-modules-hashivault/commit/05005712aafeaba8b79833ef473fcbcb5e52289a

**Comment by simonmacklin** [comment]
Hi @TerryHowe 

I have figured it out.  It was just late :)

**Comment by TerryHowe** [comment]
I think we are done with this
