### ISSUE TITLE
hashivault_read_to_file does not mesh well with bastion hosts and firewalls

### ISSUE THREAD

**Issue by mattymo** [TerryHowe/ansible-modules-hashivault#66]
Much to my surprise, the module requires that the read operation takes place on the local ansible host. First of all, that adds a python dependency on the Ansible host that I wasn't planning on. Secondly, it requires that I can route from my Ansible host to the Vault host. In my case, that's not allowed. 

I would prefer if the action was run on the target node that wants to run hashivault_read_to_file. Can you explain why this task needs to be local and if we could make it configurable?

**Comment by TerryHowe** [comment]
Okay, mentioning hashivault_read_to_file is a very odd module and that part threw me off on this.  I'm afraid there isn't much I can do about this if Anisble doesn't have Vault read access, it isn't going to be able to read secrets.
