### ISSUE TITLE
Vault Secret Engine 2

### ISSUE THREAD

**Issue by willwh** [TerryHowe/ansible-modules-hashivault#82]
I can do the following using the Vault CLI client:

```
$ vault kv list secret/certificates
Keys
----
cert1.domain.com
cert2.domain.com
cert3.domain.com
```

My Secret Engine config looks like so:

![image](https://user-images.githubusercontent.com/398396/44599627-cad43e00-a78b-11e8-8b88-4015461ade1d.png)

With some tasks like so in play:

```
tasks:
    - hashivault_list:
        secret: 'secret/certificates'
      register: cert_list
      delegate_to: localhost
    - debug:
        var: cert_list
```

I would expect to have a list, however, it's empty:

```
TASK [debug] ********************************************************************************************************************************************************************************************************************************************************
ok: [nsdnginx1] => {
    "cert_list": {
        "changed": false, 
        "failed": false, 
        "rc": 0, 
        "secrets": []
    }
}
```

**Comment by drewmullen** [comment]
whats the problem

**Comment by willwh** [comment]
@drewmullen pounding on the keyboard too hard, I didn't realize I had created an issue ;)

**Comment by willwh** [comment]
Indeed, and that works in some cases, i.e. setting a variable can be done like this:

```
{{ lookup('hashivault', '/secret/data/certificates/cert1.domain.com', 'data')[\"crt\"] }} // this would fetch the `crt` key's value
```

The above syntax does not work in `jinja` templates......

It also looks like `hashivault_read` and `hashivault_list` do no work in this situation at all.......

If you've had success, I'd love to hear more about said workarounds. I'm `willwh` on Freenode IRC if you are there too and want to chat.....

**Comment by willwh** [comment]
i.e. the following doesn't produce a list: ```
tasks:
    - hashivault_list:
        secret: 'secret/data/certificates'
      register: cert_list
      delegate_to: localhost
    - debug:
        var: cert_list
```

Which based on my provided `vault` CLI command at the top, I'd expect the module to be able to handle this too.

**Comment by willwh** [comment]
I'm just using syntax like this in my jinja templates:
```
{{ lookup('hashivault', '/secret/data/certificates/STAR.domain.com', 'data')["key"] }}
```

I don't have time to debug the `hashivault_list` issue currently, maybe I can get back to that in a week.

**Comment by drewmullen** [comment]
make this change to your hvac/v1/__init__.py and it should work

https://github.com/hvac/hvac/pull/254

**Comment by TerryHowe** [comment]
For true compatibility, sounds like this module needs to use https://hvac.readthedocs.io/en/latest/usage/secrets_engines/kv_v2.html

**Comment by TerryHowe** [comment]
Closing as dup https://github.com/TerryHowe/ansible-modules-hashivault/issues/68
