### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Dudesons** [TerryHowe/ansible-modules-hashivault#83]
Hi,

I would like to use the contribution added by this commit: https://github.com/TerryHowe/ansible-modules-hashivault/commit/f51143cf28e0d5bd2486e3eb13adb5d76387cdcd
But there is no release on pip with this commit.

@TerryHowe do you have an ETA for the release generation ?

**Comment by TerryHowe** [comment]
Sorry, I've been waiting on another change that has been slow coming.  Released 3.9.7
