### ISSUE TITLE
Lookup plugin doesn't work with environment vars in tasks.

### ISSUE THREAD

**Issue by m4dm4rtig4n** [TerryHowe/ansible-modules-hashivault#87]
When i set VAULT_ADDR directly in tasks with environment parameter, hashivault lookup plugin doesn't load vars.

Exemple :

```
    - name: USER Create User
      tags: account_create_user
      environment:
        VAULT_ADDR: "{{ vault.url }}"
        VAULT_TOKEN: "{{ account_vault.root_token }}"
        VAULT_SKIP_VERIFY: true    
      vars:
        vault_path: "/test/{{ item }}"
        vault_username: "{{ lookup('hashivault', vault_path, 'username') }}"
        vault_password: "{{ lookup('hashivault', vault_path, 'password') }}"
        vault_state:    "{{ lookup('hashivault', vault_path, 'state') }}"
        vault_key:      "{{ lookup('hashivault', vault_path, 'key') }}"
        account_home:   "/home/{{ vault_username }}"          
      with_items: "{{ account_group_fusion }}"
      user:
        name:            "{{ vault_username }}"
        comment:         "{{ account_description }}"
        shell:           "{{ account_shell }}"
        password:        "{{ vault_password|password_hash('sha512') }}"
        groups:          "{{ account_groups }}"
        createhome:      "{{ account_createhome }}"
        home:            "{{ account_home }}"
        state:           "{{ vault_state }}"
        update_password: "{{ account_reset_password }}"
```

Output : 

> An unhandled exception occurred while templating '{{ lookup('hashivault', vault_path, 'username') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'hashivault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Error reading vault /test/test@test.net/username: Exception: HTTPSConnectionPool(host='127.0.0.1', port=8200): Max retries exceeded with url: /v1/test/test@test.net (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fad10ef4b50>: Failed to establish a new connection: [Errno 111] Connection refused',))

PS : vault.url  is not https://127.0.0.1:8200

**Comment by TerryHowe** [comment]
The environment keyword only affects remote task execution, not the 'local' environment which is what lookups run under.   This is an ansible thing.

Maybe there is something else that could be done to pass parameters to the lookup plugin
https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/plugins/lookup/hashivault.py#L74

It is really designed though to use regular environment variables.

**Comment by m4dm4rtig4n** [comment]
In my case, i have a lot of roles with a lot of token and i set one token by role/project for security.

I try to edit an action plugin with your exemple in https://terryhowe.wordpress.com/2016/05/02/setting-ansible-module-defaults-using-action-plugins/
But its my first action plugin and i have difficulty to make this...

Ansible tasks : 
```
   - name: Load HashiVault Configuration
      hashivault_config:
        url: "https://test.test"
        token: "test"
        verify: False
```

But Ansible return : 
```
The module hashivault_config was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git pull --rebase' to correct this problem.
```

Action plugin "hashivault_config" : 
```
from ansible.plugins.action import ActionBase


class ActionModule(ActionBase):

    def run(self, tmp=None, task_vars=None):

        if task_vars is None:
            task_vars = dict()
        result = super(ActionModule, self).run(tmp, task_vars)

        args = self._task.args.copy()
        if 'url' not in args:
            args['url'] = self._templar.template('{{ url }}')
        if 'token' not in args:
            args['token'] = self._templar.template('{{ token }}')
        if 'verify' not in args:
            args['verify'] = self._templar.template('{{ verify }}')
        result.update(self._execute_module(module_args=args, task_vars=task_vars))
        self._task.register = args['register']
        return result
```

Any idea ?

**Comment by TerryHowe** [comment]
I was messing with this and came up with https://github.com/TerryHowe/ansible-modules-hashivault/pull/89

**Comment by TerryHowe** [comment]
The easy work around for you issue is use the hashivault_read module instead of the lookup plugin
https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/modules/hashivault/hashivault_read.py#L9

I'm not entirely convinced what I did in that PR is the best way to do that.

**Comment by TerryHowe** [comment]
merged
