### ISSUE TITLE
Allow use of hashivault without requiring root

### ISSUE THREAD

**Issue by danielmotaleite** [TerryHowe/ansible-modules-hashivault#90]
I'm have been trying trying to use hashivault as much as standalone as possible, ie: not requiring root to install hashivault and be able to run directly everything after a git clone... but i'm failing hard, ansible do not even search for the module in other places

i did open a bug in ansible:
https://github.com/ansible/ansible/issues/46004

but they report it's not possible right now... 

Have you any workaround for this?

**Comment by TerryHowe** [comment]
I'm going to close this as dup of that other issue and add some comments to that issue
