### ISSUE TITLE
.vault_token is read with the newline

### ISSUE THREAD

**Issue by danielmotaleite** [TerryHowe/ansible-modules-hashivault#91]
When using the module with the vault_token, it reads the file with the `\n` and fails
One can strip that from the file, but the module should be flexible and ignore any newline, as vaut do. so this simple fix solve this issue:

```
diff --git a/ansible/module_utils/hashivault.py b/ansible/module_utils/hashivault.py
index b548457..dc2d14a 100644
--- a/ansible/module_utils/hashivault.py
+++ b/ansible/module_utils/hashivault.py
@@ -88,5 +88,5 @@ def hashivault_default_token():
     token_file = os.path.expanduser('~/.vault-token')
     if os.path.exists(token_file):
         with open(token_file, 'r') as f:
-            return f.read()
+            return f.read().rstrip()
     return ''

```

**Comment by TerryHowe** [comment]
That went out I think 5/18 v3.9.5 https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/ansible/module_utils/hashivault.py#L100

You must be using an older version.
