### ISSUE TITLE
not able to create a branch

### ISSUE THREAD

**Issue by simonmacklin** [TerryHowe/ansible-modules-hashivault#93]
Hi 

I am sorry if this is the wrong place to put this.  I have started to write the code to allow the module to create AWS backed roles, but I am not able to push the branch I created locally up.

Kind Regards

Simon

**Comment by TerryHowe** [comment]
It doesn't look like you forked the repo.  You need to fork the repo, clone your fork, create a branch on the fork, push the branch and then do a PR to my repo from your fork.

Sounds like a very valuable feature, let me know if you need more help.

**Comment by simonmacklin** [comment]
That makes sense.  Sorry about that.

Thanks Terry
