### ISSUE TITLE
Example of getting secrets from kv via approle

### ISSUE THREAD

**Issue by samitpal** [TerryHowe/ansible-modules-hashivault#95]
I did not see any mailing list to ask question, hence creating this issue.

I'm interested in a playbook where I need to access secrets from KV using approle. Basically I want to login to the approle using role_id, secret_id and then from the token received (the token ) post a successful login I want to access the secret from KV. Is that workflow possible using this ansible module?

**Comment by TerryHowe** [comment]
Well, there is a bunch of extra stuff in here because it is a test, but this might be your best example:

https://github.com/TerryHowe/ansible-modules-hashivault/blob/master/functional/test_approle.yml

After configuring approle, ti works just like anything else except you have approle credentials
