### ISSUE TITLE
hvac 0.7.0 breaks hashivault_status

### ISSUE THREAD

**Issue by bootswithdefer** [TerryHowe/ansible-modules-hashivault#99]
hvac 0.7.0 deprecated a lot of the API (see https://github.com/hvac/hvac/releases/tag/v0.7.0) and broke hashivault_status.

Changing this line:
https://github.com/TerryHowe/ansible-modules-hashivault/blob/77aa207583130b7dac0454f6244beb2f0576ce85/ansible/modules/hashivault/hashivault_status.py#L78

to this fixed it for me:
`return {'status': client.sys.read_seal_status()} `

**Comment by TerryHowe** [comment]
Resolved in release 3.10.0
